### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by JoeMurray** [eileenmcnaughton/feature_manage_relationships_vbo#1]
Looking at https://github.com/eileenmcnaughton/feature_manage_relationships_vbo/blob/master/feature_manage_relationships_vbo.views_default.inc made me think that a bunch of it might have been auto-generated. Is there a tutorial you were following when you created this, and are there any tips you have for making more of these feature_manage_*_vbo modules?

**Comment by eileenmcnaughton** [comment]
I just used the features module and exported it as a feature

**Comment by JoeMurray** [comment]
Thanks.
